### PR TITLE
👍 Add GitHub Style

### PR DESCRIPTION
**Pull request by Pittan**
I added support for copy and pasting GitHub style sentences.

sample: https://github.com/facebook/create-react-app/pull/7465

### CODE REVIEW

**Comment by Pittan** [comment]
@rch850 yoroshiku-onegai-shimasu 🙇‍♀

**Comment by rch850** [comment]
@Pittan Thank you for sending PR.

In the sample case, `git checkout` and `git merge` fail.

Sample Input:
> eps1lon wants to merge 3 commits into facebook:add-babel-plugin-optimize-react from eps1lon:optimize-react-preset-integration

Sample Result:
```bash
git fetch origin
git checkout origin/facebook:add-babel-plugin-optimize-react # fails
git merge --no-ff origin/eps1lon:optimize-react-preset-integration # fails
```

I have no problem to merge this PR but are these failure cause problem on you?

**Comment by Pittan** [comment]
@rch850 
I was supposed to use this script inside my organization repository that I have write access.  
So the sample repository I pasted was not appropriate.  
(e.g. `username wants to merge 1 commit into master-branch from dev/feature-branch`)

And... I don't have any problems to merge this either.

**Comment by rch850** [comment]
Then... there are no problem to push this merge button. LGTM 👍

**Pull request merged**
